### ISSUE TITLE
fcn.run时的一个问题

### ISSUE THREAD

**Issue by Jiajunwei** [SamuelLAN/jdPigRecognition#1]
您好，我在跑fcn.run时遇到这样一个问题，您能帮忙看下吗：
step: 376 (377|99.73%) / 37700|1.00% 		
 best_val_loss: 28.10 	 

Saving model to fcn_2018_01_04_20_38_03 ...
Finish saving model 
step: 754 (377|0.00%) / 37700|2.00% 		
 best_val_loss: 9.84 	 

Saving model to fcn_2018_01_04_20_38_03 ...
Finish saving model 
step: 1130 (377|99.73%) / 37700|3.00% 		
 best_val_loss: 7.90 	 

Saving model to fcn_2018_01_04_20_38_03 ...
Finish saving model 
step: 1508 (377|0.00%) / 37700|4.00% 		
 best_val_loss: 2.89 	 

Saving model to fcn_2018_01_04_20_38_03 ...
Finish saving model 
step: 1884 (377|99.73%) / 37700|5.00% 		
 best_val_loss: 2.26 	 

Saving model to fcn_2018_01_04_20_38_03 ...
Finish saving model 
step: 9802 (377|0.00%) / 37700|26.00% 		
Restoring model to fcn_2018_01_04_20_38_03 ...
Finish restoring 

Start rebuilding model ...
Finish building model

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by Jiajunwei** [comment]
我简单查了下说是内存不足，也可以看到%5以后是不断叠加的，为什么会是这样呢，我改怎样解决呢。

**Comment by SamuelLAN** [comment]
你好，rebulid model 会申请大概500M的内存，rebuild model后网络会重新 init global variables，这时也是需要申请500M甚至更多的内存; 因为我自己电脑本身内存比较大，所以在加载数据方面我采用了一次性全部加载进内存的方式，导致占用内存比较多，如果电脑内存不够确实会影响网络的运行。
有两种方式可以修改，1，将load.py修改成使用数据时才加载数据，这样内存的占用就能降低; 可以参考 classify/load.py，里面采用的是异步按需加载数据; 2, 其实你刚才运行的程序已经运行好了，只是rebulid测试没有成功而已，你可以将run注释，然后运行test_model，注意要修改 test rebuild 的 model 为上次程序保存的model

**Comment by Jiajunwei** [comment]
非常感谢

**Comment by SamuelLAN** [comment]
不用谢
