### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by skq17** [SamuelLAN/jdPigRecognition#2]
亲爱的博主：
	你好！我是清华大学的学生，研究分类问题。最近想补充一批数据，京东的猪脸识别数据集应当经过较好的清洗，但是他们的下载端口已关闭。想请问你们是否还留有京东猪脸识别的训练集？求分享～～谢谢博主！我的邮箱是skq17@mails.tsinghua.edu.cn

**Comment by SamuelLAN** [comment]
你好，回你邮箱了

**Comment by jiangliubang** [comment]
博主你好！能发一下猪脸识别的数据集吗？我的邮箱是jiangliubang2012@163.com,万分感谢！

**Comment by xmaj2008** [comment]
同求数据集，求博主或者小伙伴发个数据集到邮箱，谢谢 xmaj2008@126.com

**Comment by BJTUJia** [comment]
@SamuelLAN 博主你好，我是北京交通大学的学生，最近做个小项目亟需京东猪脸的数据集，请问您还有存备份吗？如果有的话能给我发一下吗？万分感谢。我的邮箱是 12112059@bjtu.edu.cn 或 15120074732@163.com, 期待您的回复！
