### ISSUE TITLE
收敛效果慢

### ISSUE THREAD

**Issue by hahaliu1029** [SamuelLAN/jdPigRecognition#3]
你好，我用你vgg16_2里的文件直接训练，为啥收敛效果特别慢？？？

**Comment by SamuelLAN** [comment]
你是不是没改文件里的参数，里面的学习率需要重新修改一下，改成文件里注释掉的那个，因为目前文件里的学习率是对已经训练很久后的模型再训练的学习率，初始学习率要比它大很多，因为学习率太小所以才会收敛慢，你把学习率改大就好
