### ISSUE TITLE
'http://www.lin-baobao.com/model/vgg16.npy'無法下載怎麽辦？

### ISSUE THREAD

**Issue by xiaoyuaxiaoyu** [SamuelLAN/jdPigRecognition#4]

**Comment by SamuelLAN** [comment]
Try again now.

**Comment by xiaoyuaxiaoyu** [comment]
可以下载了，正在下载中，谢谢大佬。


 
---原始邮件---
发件人: "Yusen Lin"<notifications@github.com>
发送时间: 2019年4月18日(星期四) 下午2:59
收件人: "SamuelLAN/jdPigRecognition"<jdPigRecognition@noreply.github.com>;
抄送: "xiaoyuaxiaoyu"<sunxiaoyu95@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [SamuelLAN/jdPigRecognition] 'http://www.lin-baobao.com/model/vgg16.npy'無法下載怎麽辦？ (#4)



Try again now.
