### ISSUE TITLE
你好，我问一下数据加载的问题

### ISSUE THREAD

**Issue by wangliqiang7** [SamuelLAN/jdPigRecognition#6]
你好，我只在保存数据的文件夹里放了十几张图片，我用了三块8g显卡去跑，然后跑的时候，显存还是不够用，这有可能是什么造成的呀

**Comment by SamuelLAN** [comment]
你好，你是跑的哪个文件？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wliq <notifications@github.com>
发送时间: 2019年6月30日 22:53
收件人: SamuelLAN/jdPigRecognition <jdPigRecognition@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[SamuelLAN/jdPigRecognition] 你好，我问一下数据加载的问题 (#6)




你好，我只在保存数据的文件夹里放了十几张图片，我用了三块8g显卡去跑，然后跑的时候，显存还是不够用，这有可能是什么造成的呀
