### ISSUE TITLE
根本跑不起来模型，一个接着一个bug,有跑的通的吗？

### ISSUE THREAD

**Issue by codylcs** [SamuelLAN/jdPigRecognition#7]

**Comment by SamuelLAN** [comment]
。。。全部都跑得通啊


你应该是环境错了吧，你是python2还是3，环境需要python27


另外，需要注意你自己的tensorflow版本，你检查过你的版本是否兼容吗


------------------ 原始邮件 ------------------
发件人: codylcs <notifications@github.com>
发送时间: 2019年7月20日 22:40
收件人: SamuelLAN/jdPigRecognition <jdPigRecognition@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[SamuelLAN/jdPigRecognition] 根本跑不起来模型，一个接着一个bug,有跑的通的吗？ (#7)

**Comment by codylcs** [comment]
好的 那我再调试下

**Comment by qihao0423** [comment]
求教！数据的链接应该已经不能用了，怎么可以调通代码
